# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5bcf826801b7097d7f0f87ea479e66f3"
name = "papa-popup"
handle = "papa-popup"
application_url = "https://puts-functionality-una-hidden.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_script_tags,read_script_tags"

[auth]
redirect_urls = ["https://puts-functionality-una-hidden.trycloudflare.com/auth/callback", "https://puts-functionality-una-hidden.trycloudflare.com/auth/shopify/callback", "https://puts-functionality-una-hidden.trycloudflare.com/api/auth/callback"]
include_config_on_deploy = true
[pos]
embedded = false
