# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5bcf826801b7097d7f0f87ea479e66f3"
name = "papa-popup"
handle = "papa-popup"
application_url = "https://smartpop-revenue-engine.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[webhooks]
api_version = "2024-07"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request"]
uri = "/webhooks/customers/data_request"

[[webhooks.subscriptions]]
compliance_topics = ["customers/redact"]
uri = "/webhooks/customers/redact"

[[webhooks.subscriptions]]
compliance_topics = ["shop/redact"]
uri = "/webhooks/shop/redact"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_script_tags,read_script_tags,read_themes"

[auth]
redirect_urls = ["https://smartpop-revenue-engine.vercel.app/auth/callback", "https://smartpop-revenue-engine.vercel.app/auth/shopify/callback", "https://smartpop-revenue-engine.vercel.app/api/auth/callback"]
include_config_on_deploy = true
[pos]
embedded = false
